// Oracle server suite: the conformance contract against a live Oracle
// Database Free (gvenzl/oracle-free), plus everything Oracle-specific —
// RETURNING ... INTO ids, '' IS NULL semantics, implicit-commit DDL in
// migrations, PL/SQL blocks through exec(), FOR UPDATE NOWAIT conflicts.
//
// Connection from SALT_ORACLE_CONNECT / SALT_ORACLE_SYSTEM_PASSWORD
// (defaults match tests/containers/docker-compose.yml). No reachable server
// → exit 77 = ctest SKIP. Each run works as its own database user, dropped
// on exit, so reruns are clean.

#include <saltherring/saltherring.hpp>
#include <saltherring/oracle.hpp>

#include "conformance.hpp"
#include "server_fixture.hpp"

#include <format>
#include <string>
#include <unistd.h>

namespace {

std::string g_connect;
std::string g_user, g_password;

salt::db fresh() {
  auto d = salt::oracle::open(g_connect.c_str(), g_user.c_str(),
                              g_password.c_str());
  if (!d) servertest::skip(std::format("oracle not reachable as scratch user: {}",
                                       d.error().message));
  return std::move(*d);
}

struct [[=salt::table("ora_users")]] OraUser {
  [[=salt::auto_pk]] std::int64_t id = 0;
  [[=salt::unique{}]] std::string name;
};

// --- identity ids arrive via RETURNING ... INTO -----------------------------

void test_returning() {
  salt::db db = fresh();
  EXPECT_OK(db.create_table<OraUser>());
  OraUser a{.name = "a"}, b{.name = "b"};
  EXPECT_OK(db.insert(a));
  EXPECT_OK(db.insert(b));
  EXPECT(a.id != 0);
  EXPECT(b.id == a.id + 1);
  EXPECT(!db.raw().last_insert_id());  // unreachable by design on oracle
}

// --- '' IS NULL: surfaced, not hidden ---------------------------------------

void test_empty_string_semantics() {
  salt::db db = fresh();
  EXPECT_OK(db.create_table<OraUser>());
  // A non-optional string member left empty is a NOT NULL violation here.
  OraUser empty{.name = ""};
  auto r = db.insert(empty);
  EXPECT(!r);
  EXPECT(r.error().code == salt::errc::constraint);
}

// --- PL/SQL through exec(), splitter for plain statements -------------------

void test_exec_shapes() {
  salt::db db = fresh();
  // A PL/SQL block travels whole, inner semicolons intact.
  EXPECT_OK(db.exec("BEGIN NULL; END;"));
  // Plain statements split on top-level ';' — the conformance suite also
  // exercises this; here with a quoted ';' in the middle.
  EXPECT_OK(db.exec("CREATE TABLE exec_two (x NUMBER(19), s VARCHAR2(40)); "
                    "INSERT INTO exec_two VALUES (1, 'a;b')"));
  EXPECT_EQ(*db.scalar<std::int64_t>("SELECT COUNT(*) FROM exec_two"), 1);
  auto s = db.scalar<std::string>("SELECT s FROM exec_two");
  EXPECT_OK(s);
  EXPECT_EQ(*s, "a;b");
}

// --- number shaping ----------------------------------------------------------

void test_number_shaping() {
  salt::db db = fresh();
  EXPECT_EQ(*db.scalar<std::int64_t>("SELECT COUNT(*) FROM dual"), 1);
  EXPECT_EQ(*db.scalar<double>("SELECT 1.5 FROM dual"), 1.5);
  EXPECT_EQ(*db.scalar<double>("SELECT CAST(2.5 AS BINARY_DOUBLE) FROM dual"),
            2.5);
  EXPECT_EQ(*db.scalar<std::int64_t>(
                "SELECT CAST(9007199254740993 AS NUMBER(19)) FROM dual"),
            9007199254740993);  // > 2^53: declared precision keeps it exact
}

// --- isolation ---------------------------------------------------------------

void test_isolation() {
  salt::db db = fresh();
  EXPECT_OK(db.create_table<OraUser>());
  auto base = db.count<OraUser>().value_or(-1);

  EXPECT_OK(db.transaction([&]() -> salt::result<void> {
    OraUser u{.name = "serializable"};
    return db.insert(u).transform([](std::int64_t) {});
  }, {.iso = salt::isolation::serializable}));
  EXPECT_EQ(*db.count<OraUser>(), base + 1);

  auto ro = db.transaction([&]() -> salt::result<void> {
    OraUser u{.name = "nope"};
    return db.insert(u).transform([](std::int64_t) {});
  }, {.read_only = true});
  EXPECT(!ro);
  EXPECT_EQ(*db.count<OraUser>(), base + 1);
}

// --- migrations: DDL self-commits, tamper refused ----------------------------

void test_migrations() {
  salt::db db = fresh();

  const salt::migration good[] = {
      {.version = 1, .description = "create notes",
       .sql = "CREATE TABLE notes (id NUMBER(19) GENERATED BY DEFAULT ON NULL "
              "AS IDENTITY PRIMARY KEY, body VARCHAR2(4000) NOT NULL)",
       .down = "DROP TABLE notes"},
  };
  auto r = salt::migrate(db, good);
  EXPECT_OK(r);
  EXPECT_EQ(r->applied, 1);
  EXPECT_EQ(salt::migrate(db, good)->validated, 1);

  // Like MariaDB: a failed migration's DDL stays (implicit commit), and
  // history records nothing — the documented caveat, asserted.
  const salt::migration partial[] = {
      good[0],
      {.version = 2, .description = "half done",
       .sql = "CREATE TABLE mtx (x NUMBER(19)); NOT SQL"}};
  EXPECT(!salt::migrate(db, partial));
  EXPECT_OK(db.exec("SELECT * FROM mtx"));
  EXPECT_EQ(*db.count<salt::schema_history>(), 1);

  // Tampered history refused before its down SQL runs.
  EXPECT_OK(db.exec("UPDATE salt_schema_history "
                    "SET down_sql = 'DROP TABLE notes; DROP TABLE mtx' "
                    "WHERE version = 1"));
  auto rb = salt::rollback(db, 0);
  EXPECT(!rb);
  if (!rb) EXPECT(rb.error().code == salt::errc::migration_tampered);
  EXPECT_OK(db.exec("SELECT * FROM notes"));  // still there
}

// --- lock conflicts surface as coded errors, not hangs ----------------------

void test_lock_conflict() {
  salt::db a = fresh();
  salt::db b = fresh();
  EXPECT_OK(a.create_table<OraUser>());
  OraUser u{.name = "contested"};
  EXPECT_OK(a.insert(u));

  EXPECT_OK(a.exec("SET TRANSACTION READ WRITE"));
  EXPECT_OK(a.execute("UPDATE ora_users SET name = 'a holds it' WHERE id = ?",
                      u.id));
  // FOR UPDATE NOWAIT fails immediately (ORA-00054) instead of blocking.
  auto blocked = b.query<OraUser>(
      salt::unchecked_sql{"WHERE id = ? FOR UPDATE NOWAIT"}, u.id);
  EXPECT(!blocked);
  EXPECT_OK(a.exec("ROLLBACK"));
  EXPECT_OK(b.execute("UPDATE ora_users SET name = 'b got it' WHERE id = ?",
                      u.id));
}

}  // namespace

int main() {
  g_connect = servertest::env_or("SALT_ORACLE_CONNECT",
                                 "127.0.0.1:11521/FREEPDB1");
  std::string system_password =
      servertest::env_or("SALT_ORACLE_SYSTEM_PASSWORD", "salt");
  g_user = std::format("salt_run_{}", getpid());
  g_password = "scratch";

  {  // scratch user for this run; also the reachability probe
    auto sys = salt::oracle::open(g_connect.c_str(), "system",
                                  system_password.c_str());
    if (!sys) servertest::skip(std::format("oracle not reachable: {}",
                                           sys.error().message));
    auto mk = sys->exec(salt::unchecked_sql{std::format(
        "CREATE USER {} IDENTIFIED BY {} QUOTA UNLIMITED ON USERS; "
        "GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO {}",
        g_user, g_password, g_user)});
    if (!mk) servertest::skip(std::format("cannot create scratch user: {}",
                                          mk.error().message));
  }

  failures += salt::conformance::run([] { return fresh(); });
  test_returning();
  test_empty_string_semantics();
  test_exec_shapes();
  test_number_shaping();
  test_isolation();
  test_migrations();
  test_lock_conflict();

  {  // best-effort cleanup
    auto sys = salt::oracle::open(g_connect.c_str(), "system",
                                  system_password.c_str());
    if (sys)
      (void)sys->exec(salt::unchecked_sql{
          std::format("DROP USER {} CASCADE", g_user)});
  }
  return servertest::finish("oracle");
}
